spring:
  application.name: Reseller Ms
  threads.virtual.enabled: true

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
    profile:
      active: default

    webflux:
      base-path: ${CONTEXT_PATH:/reseller}

  datasource:
    driver-class-name: org.h2.Driver
    password:
    url: jdbc:h2:mem:tsg;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: sa
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      hibernate:
        ddl-auto: update


logging:
  level:
    root: trace
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
    reactor.netty: trace
    io.netty: trace